apiVersion: v1
kind: Service
metadata:
    name: hyperactive-clone-service
spec:
    type: LoadBalancer
    selector:
        app: hyperactive-clone
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
